default_roles:
  - system
  - bash
  - bat
  - btop
  - flatpak
  - fonts
  - fzf
  - gh
  - git
  - go
  - kitty
  - lazygit
  - lsd
  - lua
  - neovim
  - npm
  - nvm
  - python
  - starship
  - tldr
  - tmux
  - zoxide
  - zsh

go:
  packages:
    - package: github.com/go-task/task/v3/cmd/task@latest
      cmd: task
    - package: github.com/gcla/termshark/v2/cmd/termshark@v2.4.0
      cmd: termshark
    # - package: github.com/stillmatic/chat@latest
    #   cmd: chat
