default_roles:
  - system
  - 1password
  - asciiquarium
  - bash
  - bat
  - btop
  - discord
  - docker
  - flatpak
  - fonts
  - fzf
  - git
  - go
  - hammerspoon
  - helm
  - k8s
  - k9s
  - kitty
  - lazygit
  - lsd
  - lua
  - nala
  - neofetch
  - neovim
  - nerdfetch
  - npm
  - nvm
  - obsidian
  - podman
  - pwsh
  - python
  - raycast
  - ruby
  - rust
  - ssh
  - sshfs
  - starship
  - taskfile
  - terraform
  - tldr
  - tmate
  - tmux
  - tshark
  - zellij
  - spotify
  - zoxide
  - zsh

git_user_name: "TechDufus"
op_git_user_email_path: "op://Personal/TechDufus GitHub/email"
op:
  git:
    user:
      email: "op://Personal/TechDufus GitHub/email"
    allowed_signers: "op://Personal/TechDufus SSH/allowed_signers"
  ssh:
    github:
      techdufus:
        private_key: "op://Personal/TechDufus SSH/private key?ssh-format=openssh"
        public_key: "op://Personal/TechDufus SSH/public key"
  openai:
    key: "op://Personal/Openai/OPENAI_KEY - Project"

flatpak_packages:
  - md.obsidian.Obsidian

k8s:
  repo_version: "v1.26"

helm:
  repos:
    - name: traefik
      url: https://helm.traefik.io/traefik

go:
  packages:
    - package: github.com/go-task/task/v3/cmd/task@latest
      cmd: task
    - package: github.com/gcla/termshark/v2/cmd/termshark@v2.4.0
      cmd: termshark
    # - package: github.com/stillmatic/chat@latest
    #   cmd: chat
