---
- name: "Zsh | MacOSX | Install zsh"
  community.general.homebrew:
    name: zsh
    state: present

- name: "Zsh | Set default terminal"
  ansible.builtin.user:
    name: "{{ host_user }}"
    shell: /opt/homebrew/bin/zsh
  become: true
