---
- name: "Kitty | Ubuntu | Install kitty"
  ansible.builtin.apt:
    name: kitty
    state: present

- name: "Kitty | Ubuntu | Deploy Kitty Config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/kitty"
    mode: "0755"
    state: directory

- name: "Kitty | Ubuntu | Setting Base Kitty Config"
  ansible.builtin.set_fact:
    kitty_config: kitty.conf

- name: "Kitty | Ubuntu | Checking for Distribution Config: {{ ansible_distribution }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/files/kitty_{{ ansible_distribution }}.conf"
  register: kitty_distribution_config

- name: "Kitty | Ububtu | Found, Setting Kitty Config: kitty_{{ ansible_distribution }}.conf"
  ansible.builtin.set_fact:
    kitty_config: "kitty_{{ ansible_distribution }}.conf"
  when: kitty_distribution_config.stat.exists


- name: "Kitty | Ubuntu | Deploy Kitty Config: {{ kitty_config }}"
  ansible.builtin.copy:
    src: "{{ kitty_config }}"
    dest: "{{ ansible_user_dir }}/.config/kitty/kitty.conf"
    mode: "0644"
